### ISSUE TITLE
[BUG]: Unexpected behavior while recovering from a long loop time.

### ISSUE THREAD

**Issue by gerth2** [robotpy/mostrobotpy#111]
### Problem description

Discussion started here: https://discord.com/channels/176186766946992128/368993897495527424/1307652469337096193

Testcase.... a robot program set up to normally have `robotPeriodic` take 13ms to execute. One loop takes 200ms. 

Before the long loop, periodic execution is a nice steady 20ms. After the long loop, it's 13ms almost exactly. 

This continues for some time, presumably until the time has "caught up".

What's very weird is the C++ implementation has logic to prevent this... but it doesn't seem to be working as advertised ( next loop always happens at least one full period ahead of when the current one _started_).

https://github.com/wpilibsuite/allwpilib/blob/main/wpilibc/src/main/native/cpp/TimedRobot.cpp#L57C1-L59C65

There's two sides I see to this:
1) As-is, the behavior is to _average_ the total loop period to 20ms. However, for heavily-loaded user codebases, this might take a long time.
2) As-commented-in-c++ - the long loop is assumed to be a lost cause, and periodic execution returns. This means that over any finite window, you're more likely to see 20ms of execution.

I'd make an argument that on the timescales that FRC runs at, you'd rather see (2) as the preferred recovery from an unexpectedly long loop. But.... if that's questionable that's ok, I wouldn't die on that hill (Users could always make their own top-level robot class to behave like they want).

If (1) is the answer though, I'm still at a loss as to what code is causing the behavior.... and likely, the C++ wpilib code needs a comment update.

### Operating System

Windows, RoboRIO

### Installed Python Packages

```text
Package                        Version
------------------------------ ----------------
absl-py                        2.1.0
alabaster                      0.7.13
altgraph                       0.17.4
apeye                          1.4.1
apeye-core                     1.1.4
appdirs                        1.4.4
astroid                        3.0.2
asttokens                      2.4.1
autodocsumm                    0.2.11
Babel                          2.13.1
bcrypt                         4.1.2
beautifulsoup4                 4.12.2
black                          23.1.0
Brotli                         1.1.0
CacheControl                   0.13.1
certifi                        2023.7.22
cffi                           1.16.0
charset-normalizer             3.3.2
clang-format                   17.0.5
clang-tidy                     17.0.1
click                          8.1.7
colorama                       0.4.6
context-var                    0.1.1
contourpy                      1.2.0
coverage                       7.4.1
cryptography                   41.0.7
cssutils                       2.9.0
cycler                         0.12.1
data                           0.4
dataclasses                    0.6
debugpy                        1.6.7
decorator                      5.1.1
dict2css                       0.3.0
dill                           0.3.7
doc8                           0.11.2
docutils                       0.18.1
domdf-python-tools             3.7.0
executing                      2.1.0
filelock                       3.13.1
fonttools                      4.43.0
frccontrol                     2023.28
fsspec                         2024.2.0
funcsigs                       1.0.2
future                         0.18.3
gersemi                        0.9.3
gitdb                          4.0.11
GitPython                      3.1.41
grpcio                         1.66.1
html5lib                       1.1
idna                           3.4
imagesize                      1.4.1
iniconfig                      2.0.0
inliner                        0.4.1
ipython                        8.27.0
isort                          5.13.2
iterextras                     0.2.1
jedi                           0.19.1
Jinja2                         3.1.3
jsmin                          3.0.1
kiwisolver                     1.4.5
lark                           1.1.8
latex                          0.7.0
lazy-object-proxy              1.10.0
libcst                         1.1.0
line_profiler                  4.1.3
Markdown                       3.7
markdown2                      2.4.6
MarkupSafe                     2.1.3
matplotlib                     3.8.1
matplotlib-inline              0.1.7
mccabe                         0.7.0
modern-sphinx-version-warning  1.1.6
mpmath                         1.3.0
msgpack                        1.0.7
mypy-extensions                1.0.0
natsort                        8.4.0
networkx                       3.2.1
numpy                          1.26.2
opencv-python                  4.10.0.84
packaging                      23.2
pandas                         2.2.3
paramiko                       3.4.0
parso                          0.8.4
pathspec                       0.11.2
pbr                            6.0.0
pefile                         2023.2.7
phoenix6                       24.3.0
photonlibpy                    2024.2.4
pillow                         10.2.0
Pint                           0.23
pip                            24.2
platformdirs                   4.0.0
pluggy                         1.3.0
prompt_toolkit                 3.0.47
protobuf                       5.28.2
psutil                         6.0.0
pure_eval                      0.2.3
pycparser                      2.21
pyfrc                          2024.0.1
Pygments                       2.16.1
pyinstaller                    6.4.0
pyinstaller-hooks-contrib      2024.1
pylint                         3.0.3
PyNaCl                         1.5.0
pynetconsole                   2.0.4
pyntcore                       2024.2.1.2
pyparsing                      3.1.1
pytest                         7.4.4
pytest-reraise                 2.1.2
python-dateutil                2.8.2
pytz                           2024.2
pywin32-ctypes                 0.2.2
PyYAML                         6.0.1
regex                          2023.10.3
requests                       2.31.0
restructuredtext_lint          1.4.0
robotpy                        2024.2.1.2
robotpy-apriltag               2024.2.1.2
robotpy-cli                    2024.0.0
robotpy-cscore                 2024.2.1.2
robotpy-hal                    2024.2.1.2
robotpy-halsim-ds-socket       2024.2.1.2
robotpy-halsim-gui             2024.2.1.2
robotpy-halsim-ws              2024.2.1.2
robotpy-installer              2024.2.2
robotpy-playingwithfusion      2024.1.0
robotpy-rev                    2024.2.1
robotpy-romi                   2024.1.1.1
robotpy-wpilib-utilities       2024.0.0
robotpy-wpimath                2024.2.1.2
robotpy-wpinet                 2024.2.1.2
robotpy-wpiutil                2024.2.1.2
robotpy-xrp                    2024.1.1.1
ruamel.yaml                    0.18.5
ruamel.yaml.clib               0.2.8
scipy                          1.11.3
seaborn                        0.13.2
setuptools                     75.1.0
shutilwhich                    1.1.0
six                            1.16.0
smmap                          5.0.1
snowballstemmer                2.2.0
soupsieve                      2.5
Sphinx                         7.2.6
sphinx-autodoc-typehints       1.25.2
sphinx-copybutton              0.5.2
sphinx_design                  0.5.0
sphinx-hoverxref               1.3.0
sphinx-jinja2-compat           0.2.0
sphinx-notfound-page           1.0.0
sphinx-prompt                  1.8.0
sphinx-rtd-theme               2.0.0
sphinx-tabs                    3.4.4
sphinx-toolbox                 3.5.0
sphinxcontrib-applehelp        1.0.7
sphinxcontrib-devhelp          1.0.5
sphinxcontrib-htmlhelp         2.0.4
sphinxcontrib-jquery           4.1
sphinxcontrib-jsmath           1.0.1
sphinxcontrib-qthelp           1.0.6
sphinxcontrib-serializinghtml  1.1.9
sphinxcontrib-svg2pdfconverter 1.2.2
sphinxext-delta                0.2.0
sphinxext-linkcheckdiff        0.1.0
sphinxext-mimic                0.1.1
sphinxext-opengraph            0.9.0
sphinxext-photofinish          0.1.10
sphinxext-presentations        0.2.2
sphinxext-rediraffe            0.2.7
sphinxext-remoteliteralinclude 0.4.0
sphinxext-toptranslators       0.1.3
stack-data                     0.6.3
stevedore                      5.1.0
sympy                          1.12
tabulate                       0.9.0
tempdir                        0.7.1
tensorboard                    2.17.1
tensorboard-data-server        0.7.2
thop                           0.1.1-2209072238
tinycss2                       1.2.1
tomli                          2.0.1
tomlkit                        0.12.3
torch                          2.4.1+cpu
torchaudio                     2.4.1+cpu
torchvision                    0.19.1+cpu
tqdm                           4.66.1
traitlets                      5.14.3
typing_extensions              4.8.0
typing-inspect                 0.9.0
tzdata                         2024.1
urllib3                        1.26.18
wcwidth                        0.2.13
webencodings                   0.5.1
Werkzeug                       3.0.4
wheel                          0.42.0
wpiformat                      2023.36
wpilib                         2024.2.1.2
wrapt                          1.16.0
zopfli                         0.2.3
```

![image](https://github.com/user-attachments/assets/50d1b874-5483-49ad-8171-2d20434c333e)

### Reproducible example code

```text
import wpilib
import time

class R(wpilib.TimedRobot):
    
    def __init__(self) -> None:
        super().__init__()
        self.f = open("times.csv", "w")
        self.c = 0
        self.prevLoopSart = wpilib.Timer.getFPGATimestamp()

    def robotPeriodic(self) -> None:
        loopStart = wpilib.Timer.getFPGATimestamp()
        loopDelta = loopStart - self.prevLoopSart
        self.prevLoopSart = loopStart

        self.c += 1

        if self.c == 50:
            time.sleep(0.2) # oops one really long loop
        else:
            time.sleep(0.013) # normal loop execution

        if self.c > 300:
            exit()

        self.f.write(f"{loopDelta},\n")
        self.f.flush()

############################################################
## This produces times.csv with the following contents:

0.020764999999999922,
0.020272999999999985,
0.019279000000000046,
0.019947000000000048,
0.019915999999999934,
0.019580000000000042,
0.020637000000000016,
0.02005799999999991,
0.019855000000000067,
0.01952900000000002,
0.02011599999999991,
0.01982600000000001,
0.020731000000000055,
0.019822000000000006,
0.019863999999999993,
0.020724999999999993,
0.019020999999999955,
0.019732000000000083,
0.020530999999999855,
0.01964800000000011,
0.019855999999999874,
0.021024000000000154,
0.020518000000000036,
0.018700999999999857,
0.020064000000000082,
0.01988499999999993,
0.019805000000000073,
0.019879999999999898,
0.020094000000000056,
0.01993299999999998,
0.02029100000000006,
0.01959299999999997,
0.020651999999999893,
0.019419999999999993,
0.021452000000000027,
0.018782999999999994,
0.020803000000000127,
0.01972700000000005,
0.019359999999999822,
0.019686000000000092,
0.021344999999999947,
0.019517000000000007,
0.01991900000000002,
0.019509,
0.02137000000000011,
0.019138999999999795,
0.01958200000000021,
0.020595999999999837,
0.019144999999999968,
0.020961000000000007,
0.2054910000000001, # NOTE - LONG LOOP HERE
0.013508999999999993,
0.01340499999999989,
0.013501000000000207,
0.013511999999999968,
0.013566999999999885,
0.013214999999999977,
0.013441999999999954,
0.01327900000000004,
0.013800999999999952,
0.01370300000000002,
0.013511999999999968,
0.013548000000000116,
0.013866999999999852,
0.013441000000000258,
0.013597999999999999,
0.013659999999999783,
0.013367000000000129,
0.013468000000000035,
0.0135320000000001,
0.01375499999999974,
0.013806000000000207,
0.014664999999999928,
0.013739000000000168,
0.013527999999999984,
0.01353499999999963,
0.013622000000000245,
0.013535000000000075,
0.013408999999999782,
0.013653000000000137,
0.02010299999999976, # Note seems to "recover" right about here
0.020388000000000073,
0.01886499999999991,
0.02036400000000027,
0.019597999999999782,
0.020999000000000212,
0.019489999999999785,
0.019849999999999923,
0.019925000000000193,
# ... more 20ms ish loops
```

**Comment by virtuald** [comment]
That commit in Timed robot was done recently, and you have 2024 installed. I haven't tried it, but I would expect the beta to contain that fix. On Nov 17, 2024 10:21 AM, Chris Gerth ***@***.***> wrote:
Problem description
Discussion started here: https://discord.com/channels/176186766946992128/368993897495527424/1307652469337096193
Testcase.... a robot program set up to normally have robotPeriodic take 13ms to execute. One loop takes 200ms.
Before the long loop, periodic execution is a nice steady 20ms. After the long loop, it's 13ms almost exactly.
This continues for some time, presumably until the time has "caught up".
What's very weird is the C++ implementation has logic to prevent this... but it doesn't seem to be working as advertized.
https://github.com/wpilibsuite/allwpilib/blob/main/wpilibc/src/main/native/cpp/TimedRobot.cpp#L57C1-L59C65
Operating System
Windows, RoboRIO
Installed Python Packages
Package                        Version
------------------------------ ----------------
absl-py                        2.1.0
alabaster                      0.7.13
altgraph                       0.17.4
apeye                          1.4.1
apeye-core                     1.1.4
appdirs                        1.4.4
astroid                        3.0.2
asttokens                      2.4.1
autodocsumm                    0.2.11
Babel                          2.13.1
bcrypt                         4.1.2
beautifulsoup4                 4.12.2
black                          23.1.0
Brotli                         1.1.0
CacheControl                   0.13.1
certifi                        2023.7.22
cffi                           1.16.0
charset-normalizer             3.3.2
clang-format                   17.0.5
clang-tidy                     17.0.1
click                          8.1.7
colorama                       0.4.6
context-var                    0.1.1
contourpy                      1.2.0
coverage                       7.4.1
cryptography                   41.0.7
cssutils                       2.9.0
cycler                         0.12.1
data                           0.4
dataclasses                    0.6
debugpy                        1.6.7
decorator                      5.1.1
dict2css                       0.3.0
dill                           0.3.7
doc8                           0.11.2
docutils                       0.18.1
domdf-python-tools             3.7.0
executing                      2.1.0
filelock                       3.13.1
fonttools                      4.43.0
frccontrol                     2023.28
fsspec                         2024.2.0
funcsigs                       1.0.2
future                         0.18.3
gersemi                        0.9.3
gitdb                          4.0.11
GitPython                      3.1.41
grpcio                         1.66.1
html5lib                       1.1
idna                           3.4
imagesize                      1.4.1
iniconfig                      2.0.0
inliner                        0.4.1
ipython                        8.27.0
isort                          5.13.2
iterextras                     0.2.1
jedi                           0.19.1
Jinja2                         3.1.3
jsmin                          3.0.1
kiwisolver                     1.4.5
lark                           1.1.8
latex                          0.7.0
lazy-object-proxy              1.10.0
libcst                         1.1.0
line_profiler                  4.1.3
Markdown                       3.7
markdown2                      2.4.6
MarkupSafe                     2.1.3
matplotlib                     3.8.1
matplotlib-inline              0.1.7
mccabe                         0.7.0
modern-sphinx-version-warning  1.1.6
mpmath                         1.3.0
msgpack                        1.0.7
mypy-extensions                1.0.0
natsort                        8.4.0
networkx                       3.2.1
numpy                          1.26.2
opencv-python                  4.10.0.84
packaging                      23.2
pandas                         2.2.3
paramiko                       3.4.0
parso                          0.8.4
pathspec                       0.11.2
pbr                            6.0.0
pefile                         2023.2.7
phoenix6                       24.3.0
photonlibpy                    2024.2.4
pillow                         10.2.0
Pint                           0.23
pip                            24.2
platformdirs                   4.0.0
pluggy                         1.3.0
prompt_toolkit                 3.0.47
protobuf                       5.28.2
psutil                         6.0.0
pure_eval                      0.2.3
pycparser                      2.21
pyfrc                          2024.0.1
Pygments                       2.16.1
pyinstaller                    6.4.0
pyinstaller-hooks-contrib      2024.1
pylint                         3.0.3
PyNaCl                         1.5.0
pynetconsole                   2.0.4
pyntcore                       2024.2.1.2
pyparsing                      3.1.1
pytest                         7.4.4
pytest-reraise                 2.1.2
python-dateutil                2.8.2
pytz                           2024.2
pywin32-ctypes                 0.2.2
PyYAML                         6.0.1
regex                          2023.10.3
requests                       2.31.0
restructuredtext_lint          1.4.0
robotpy                        2024.2.1.2
robotpy-apriltag               2024.2.1.2
robotpy-cli                    2024.0.0
robotpy-cscore                 2024.2.1.2
robotpy-hal                    2024.2.1.2
robotpy-halsim-ds-socket       2024.2.1.2
robotpy-halsim-gui             2024.2.1.2
robotpy-halsim-ws              2024.2.1.2
robotpy-installer              2024.2.2
robotpy-playingwithfusion      2024.1.0
robotpy-rev                    2024.2.1
robotpy-romi                   2024.1.1.1
robotpy-wpilib-utilities       2024.0.0
robotpy-wpimath                2024.2.1.2
robotpy-wpinet                 2024.2.1.2
robotpy-wpiutil                2024.2.1.2
robotpy-xrp                    2024.1.1.1
ruamel.yaml                    0.18.5
ruamel.yaml.clib               0.2.8
scipy                          1.11.3
seaborn                        0.13.2
setuptools                     75.1.0
shutilwhich                    1.1.0
six                            1.16.0
smmap                          5.0.1
snowballstemmer                2.2.0
soupsieve                      2.5
Sphinx                         7.2.6
sphinx-autodoc-typehints       1.25.2
sphinx-copybutton              0.5.2
sphinx_design                  0.5.0
sphinx-hoverxref               1.3.0
sphinx-jinja2-compat           0.2.0
sphinx-notfound-page           1.0.0
sphinx-prompt                  1.8.0
sphinx-rtd-theme               2.0.0
sphinx-tabs                    3.4.4
sphinx-toolbox                 3.5.0
sphinxcontrib-applehelp        1.0.7
sphinxcontrib-devhelp          1.0.5
sphinxcontrib-htmlhelp         2.0.4
sphinxcontrib-jquery           4.1
sphinxcontrib-jsmath           1.0.1
sphinxcontrib-qthelp           1.0.6
sphinxcontrib-serializinghtml  1.1.9
sphinxcontrib-svg2pdfconverter 1.2.2
sphinxext-delta                0.2.0
sphinxext-linkcheckdiff        0.1.0
sphinxext-mimic                0.1.1
sphinxext-opengraph            0.9.0
sphinxext-photofinish          0.1.10
sphinxext-presentations        0.2.2
sphinxext-rediraffe            0.2.7
sphinxext-remoteliteralinclude 0.4.0
sphinxext-toptranslators       0.1.3
stack-data                     0.6.3
stevedore                      5.1.0
sympy                          1.12
tabulate                       0.9.0
tempdir                        0.7.1
tensorboard                    2.17.1
tensorboard-data-server        0.7.2
thop                           0.1.1-2209072238
tinycss2                       1.2.1
tomli                          2.0.1
tomlkit                        0.12.3
torch                          2.4.1+cpu
torchaudio                     2.4.1+cpu
torchvision                    0.19.1+cpu
tqdm                           4.66.1
traitlets                      5.14.3
typing_extensions              4.8.0
typing-inspect                 0.9.0
tzdata                         2024.1
urllib3                        1.26.18
wcwidth                        0.2.13
webencodings                   0.5.1
Werkzeug                       3.0.4
wheel                          0.42.0
wpiformat                      2023.36
wpilib                         2024.2.1.2
wrapt                          1.16.0
zopfli                         0.2.3

Reproducible example code
import wpilib
import time

class R(wpilib.TimedRobot):
    
    def __init__(self) -> None:
        super().__init__()
        self.f = open("times.csv", "w")
        self.c = 0
        self.prevLoopSart = wpilib.Timer.getFPGATimestamp()

    def robotPeriodic(self) -> None:
        loopStart = wpilib.Timer.getFPGATimestamp()
        loopDelta = loopStart - self.prevLoopSart
        self.prevLoopSart = loopStart

        self.c += 1

        if self.c == 50:
            time.sleep(0.2) # oops one really long loop
        else:
            time.sleep(0.013) # normal loop execution

        if self.c > 300:
            exit()

        self.f.write(f"{loopDelta},\n")
        self.f.flush()

############################################################
## This produces times.csv with the following contents:

0.020764999999999922,
0.020272999999999985,
0.019279000000000046,
0.019947000000000048,
0.019915999999999934,
0.019580000000000042,
0.020637000000000016,
0.02005799999999991,
0.019855000000000067,
0.01952900000000002,
0.02011599999999991,
0.01982600000000001,
0.020731000000000055,
0.019822000000000006,
0.019863999999999993,
0.020724999999999993,
0.019020999999999955,
0.019732000000000083,
0.020530999999999855,
0.01964800000000011,
0.019855999999999874,
0.021024000000000154,
0.020518000000000036,
0.018700999999999857,
0.020064000000000082,
0.01988499999999993,
0.019805000000000073,
0.019879999999999898,
0.020094000000000056,
0.01993299999999998,
0.02029100000000006,
0.01959299999999997,
0.020651999999999893,
0.019419999999999993,
0.021452000000000027,
0.018782999999999994,
0.020803000000000127,
0.01972700000000005,
0.019359999999999822,
0.019686000000000092,
0.021344999999999947,
0.019517000000000007,
0.01991900000000002,
0.019509,
0.02137000000000011,
0.019138999999999795,
0.01958200000000021,
0.020595999999999837,
0.019144999999999968,
0.020961000000000007,
0.2054910000000001, # NOTE - LONG LOOP HERE
0.013508999999999993,
0.01340499999999989,
0.013501000000000207,
0.013511999999999968,
0.013566999999999885,
0.013214999999999977,
0.013441999999999954,
0.01327900000000004,
0.013800999999999952,
0.01370300000000002,
0.013511999999999968,
0.013548000000000116,
0.013866999999999852,
0.013441000000000258,
0.013597999999999999,
0.013659999999999783,
0.013367000000000129,
0.013468000000000035,
0.0135320000000001,
0.01375499999999974,
0.013806000000000207,
0.014664999999999928,
0.013739000000000168,
0.013527999999999984,
0.01353499999999963,
0.013622000000000245,
0.013535000000000075,
0.013408999999999782,
0.013653000000000137,
0.02010299999999976, # Note seems to "recover" right about here
0.020388000000000073,
0.01886499999999991,
0.02036400000000027,
0.019597999999999782,
0.020999000000000212,
0.019489999999999785,
0.019849999999999923,
0.019925000000000193,
0.019870000000000054,
0.021180999999999894,
0.018629999999999924,
0.020834999999999937,
0.019219000000000097,
0.020646000000000164,
0.019759999999999778,
0.02143600000000001,
0.019112999999999936,
0.020851000000000397,
0.019111999999999796,
0.01982499999999998,
0.019864000000000104,
0.019881999999999955,
0.01967300000000005,
0.021014000000000088,
0.018728999999999996,
0.02082000000000006,
0.01987799999999984,
0.02005699999999999,
0.019695000000000018,
0.021017000000000063,
0.019114000000000075,
0.01978599999999986,
0.020001999999999853,
0.020494000000000234,
0.02032899999999982,
0.01904899999999987,
0.020982000000000056,
0.01910500000000015,
0.021856999999999793,
0.018880999999999926,
0.0194700000000001,
0.01968100000000028,
0.020509999999999806,
0.019943000000000044,
0.019770999999999983,
0.020010000000000083,
0.019743999999999762,
0.020713000000000203,
0.019625000000000004,
0.019697999999999993,
0.020744000000000096,
0.019502999999999826,
0.021247999999999934,
0.018597000000000197,
0.0204869999999997,
0.0200140000000002,
0.019482,
0.020687000000000122,
0.01980000000000004,
0.019948999999999995,
0.019477999999999884,
0.020944000000000074,
0.0189619999999997,
0.019957000000000225,
0.021298999999999957,
0.020252999999999854,
0.019157000000000313,
0.019397999999999804,
0.01996999999999982,
0.020811000000000135,
0.020011000000000223,
0.019514999999999727,
0.020036000000000165,
0.019784000000000024,
0.02152900000000013,
0.01904899999999987,
0.01987199999999989,
0.019677999999999862,
0.019919999999999938,
0.02065700000000037,
0.019838000000000022,
0.01993899999999993,
0.01981199999999994,
0.0197449999999999,
0.02078800000000003,
0.019780999999999604,
0.020023000000000124,
0.020039000000000584,
0.01962900000000012,
0.019723999999999187,
0.019696000000000602,
0.020846999999999838,
0.020306999999999853,
0.019009000000000498,
0.020953999999999695,
0.02012199999999975,
0.019254000000000104,
0.01992399999999961,
0.021475000000000577,
0.018968000000000096,
0.01996199999999959,
0.019836999999999883,
0.019984000000000002,
0.019519999999999982,
0.02042799999999989,
0.019544000000000672,
0.02084499999999956,
0.02073500000000017,
0.01889200000000013,
0.021150999999999698,
0.018459000000000003,
0.020547000000000537,
0.019902999999999338,
0.019720000000000404,
0.020190999999999626,
0.02137900000000048,
0.018442999999999543,
0.019791000000000558,
0.02008799999999944,
0.021266999999999925,
0.018799000000000454,
0.0207550000000003,
0.020270999999999262,
0.018841000000000108,
0.02167800000000053,
0.01872499999999988,
0.020497999999999905,
0.01920300000000008,
0.020445999999999742,
0.01966000000000001,
0.01981900000000003,
0.021616999999999997,
0.01853899999999964,
0.021764000000000117,
0.01824700000000057,
0.019561999999999635,
0.020604999999999762,
0.020029000000000075,
0.019735999999999976,
0.020650999999999975,
0.019747999999999877,
0.01949800000000046,
0.02167999999999992,
0.018515999999999977,
0.020092,
0.019578000000000095,
0.020813999999999666,
0.019872000000000334,
0.02750999999999948,
0.013391000000000375,
0.01855000000000029,
0.021128000000000036,
0.018927999999999834,
0.019986999999999533,
0.0203060000000006,
0.019565000000000055,
0.01993599999999951,
0.020512000000000086,
0.01964499999999969,
0.021270000000000344,
0.018921999999999883,
0.019775000000000098,
0.021408000000000094,
0.019054999999999822,
0.019562999999999775,
0.019750000000000156,
0.020931000000000033,
0.02028600000000047,
0.01948599999999967,
0.020164000000000293,
0.019600999999999758,
0.020035000000000025,
0.0199309999999997,
0.019601000000000646,
0.021256999999999415,
0.019379999999999953,
0.019610000000000127,
0.02013900000000035,
0.020192999999999905,
0.020366000000000106,
0.019559000000000104,
0.01995099999999983,
0.0205529999999996,
0.019758000000000386,
0.019519999999999982,
0.02057500000000001,
0.01933399999999974,
0.01994600000000002,
0.021747000000000405,
0.019398999999999944,
0.018667999999999907,
0.0206849999999994,
0.019603000000000037,
0.02056300000000011,
0.020010000000000083,
0.019525999999999932,
0.02027000000000001,
0.019544000000000672,
0.020159999999999734,
0.01993299999999998,
0.020596999999999532,
0.019739000000000395,
0.020019999999999705,
0.019694000000000322,
0.02148199999999978,
0.01921900000000054,
0.018957999999999586,
0.021378999999999593,
0.019391000000000602,
0.02022799999999947,
0.019415000000000404,
0.01963999999999988,
0.02132999999999985,
0.019086999999999854,
0.020615000000000272,
0.018956000000000195,
0.02954499999999971,
0.013643000000000072,
0.017445000000000377,
