### ISSUE TITLE
Adding Auto-Wi-fi Switching When Deploying Robot Code

### ISSUE THREAD

**Issue by PhantomLel** [robotpy/mostrobotpy#38]
Hi guys, I realize that this is not at all a bug or an issue with RobotPy, but would it be possible to automatically switch to the robot network when running the deploy command? I found it to be a mild annoyance to have to switch all the time and I think it would be cool to have the program automatically take care of that for you. I would love to add this feature myself, could I get some guidance on where to start?

**Comment by virtuald** [comment]
I suspect this might be challenging to implement correctly for all platforms that WPILib supports (Windows, Linux, OSX), and it would be even more challenging to implement solely in python -- I suspect there's a lot of platform-specific code that would need to run, and might change the deploy to require administrative privileges depending on the platform. Additionally, it would probably be better to do this for all FRC languages, not just for RobotPy? 

Have you looked to see what is required to programmatically change the wireless settings on Windows/Linux/OSX?

**Comment by virtuald** [comment]
I'm not going to personally work on this, and I think this would be more appropriate as a general GradleRIO/wpilib feature and should be developed there. Happy to discuss more if you have other ideas.
