### ISSUE TITLE
[BUG]: PWMMotorController.addFollower causes segfaults on motor.set

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/mostrobotpy#64]
### Problem description

When adding a follower to a `PWMMotorController` without keeping a reference to the follower, a subsequent call to `.set()` will segfault when trying to set the follower.

### Operating System

Windows, MacOS, Linux, RoboRIO, Raspbian

### Reproducible example code

```text
import wpilib

class Robot(wpilib.TimedRobot):
    def robotInit(self):
        self.motor = wpilib.PWMSparkMax(1)
        self.motor.addFollower(wpilib.PWMSparkMax(2))

    def autonomousPeriodic(self):
        self.motor.set(0.5)
```

**Comment by virtuald** [comment]
Lame.
