### ISSUE TITLE
Add __repr__ for TrapezoidProfile.constraints/state et al

### ISSUE THREAD

**Issue by virtuald** [robotpy/mostrobotpy#79]

**Comment by auscompgeek** [comment]
Don't we already have a custom `__repr__` for these?

**Comment by auscompgeek** [comment]
Oh, apparently not for Constraints, but we do - for State.

https://github.com/robotpy/mostrobotpy/blob/58d5646c55092b396d219c72c0960c0ea1282d4c/subprojects/robotpy-wpimath/gen/controls/TrapezoidProfile.yml#L61
