### ISSUE TITLE
Missing hal.simulation functions for registering sim callbacks

### ISSUE THREAD

**Issue by bhall-ctre** [robotpy/mostrobotpy#90]
### Problem description

Some of the `hal.simulation` functions for registering callbacks are missing. For example, there is no `registerSimValueChangedCallback`, even though there is a `cancelSimValueChangedCallback`. These callbacks are necessary for vendors to use WPILib sim GUI inputs.

I believe all the relevant callback APIs are in SimDeviceData.h: https://github.com/wpilibsuite/allwpilib/blob/main/hal/src/main/native/include/hal/simulation/SimDeviceData.h

### Operating System

Windows

### Installed Python Packages

```text
pyfrc                          2024.0.1
pyntcore                       2024.3.2.0
robotpy                        2024.3.2.1
robotpy-cli                    2024.0.0
robotpy-commands-v2            2024.3.1
robotpy-hal                    2024.3.2.0
robotpy-halsim-gui             2024.3.2.0
robotpy-installer              2024.2.2
robotpy-wpilib-utilities       2024.0.0
robotpy-wpimath                2024.3.2.0
robotpy-wpinet                 2024.3.2.0
robotpy-wpiutil                2024.3.2.0
wpilib                         2024.3.2.0
```

**Comment by TheTripleV** [comment]
https://github.com/robotpy/mostrobotpy/blob/main/subprojects/robotpy-hal/gen/simulation/SimDeviceData.yml

They are all manually ignored right now for some reason.

**Comment by virtuald** [comment]
Nobody ever needed them so I never bothered. It shouldn't be that bad. Which specific callbacks do you need?
