### ISSUE TITLE
cvnp false-positive noncontiguous input on windows only

### ISSUE THREAD

**Issue by truher** [robotpy/mostrobotpy#99]
### Problem description

so i'm using CameraServer on the desktop, for testing.

here's a minimal case:

```
x = CameraServer.putVideo(..)
x.putFrame(np.zeros((10,10),dtype=np.uint8))
```

trips the [contiguous-input check](https://github.com/robotpy/mostrobotpy/blob/ba97ccbca444ef6f0c7fb24503faf8029d6a4019/subprojects/robotpy-cscore/cscore/cvnp/cvnp.cpp#L203), but only on windows.  on linux, it works fine.

i'm using python 3.11.9 and robotpy 2024.3.2.1

I don't need anything else that CameraServer does, so I switched to mjpeg_streamer, which works fine.

### Operating System

Windows

**Comment by virtuald** [comment]
That user reported that downgrading numpy to a 1.x version fixed the issue for them.
